Repository kluntje/kluntje, pull requests merged in 2020-03, with the labels that each got.

#17 added unit tests for event helpers (closes #11)
  packages/js-utils/src/dom-helpers/lib/Context.ts
  packages/js-utils/src/dom-helpers/tests/forEachNode.test.ts
  packages/js-utils/src/dom-helpers/tests/onEvent.test.ts
  packages/js-utils/src/dom-helpers/tests/removeEvent.test.ts
Labels: testing

#20 added decorator example to README
  README.md
  packages/core/README.md
  packages/js-utils/README.md
Labels: documentation

#22 added contributing guide (closes #10)
  .github/CONTRIBUTING.md
  README.md
  packages/core/README.md
Labels: documentation

#25 docs(all): fix licence and repository link in package.json (closes #23)
  packages/core/package.json
  packages/js-utils/package.json
  packages/services/package.json
Labels: documentation

#28 feat(js-utils): add helper to sanitize GMT part of Date strings (closes #26)
  packages/js-utils/README.md
  packages/js-utils/src/date-helpers/index.ts
  packages/js-utils/src/date-helpers/lib/sanitizeDateGMTOffset.ts
  packages/js-utils/src/date-helpers/tests/sanitizeDateGMTOffset.test.ts
Labels: enhancement, js-utils
